CREATE TABLE summoner(
    id TEXT UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL,
    puuid TEXT UNIQUE NOT NULL,
    accountId TEXT UNIQUE NOT NULL,
    level INT NOT NULL,
    revisionDate TIMESTAMP NOT NULL,
    profileIconId INT NOT NULL
);
